services:
  postgres:
    image: postgres:15
    container_name: mega-postgres
    environment:
      POSTGRES_USER: mega
      POSTGRES_PASSWORD: mega
      POSTGRES_DB: mega-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: